app/models/user_models.py
from flask_security import UserMixin, RoleMixin
from app import db


class Role(db.Document, RoleMixin):
    name = db.StringField(max_length=80, unique=True)
    description = db.StringField(max_length=255)

    def __unicode__(self):
        return self.name


class User(db.Document, UserMixin):
    email = db.StringField(max_length=255)
    password = db.StringField(max_length=255)
    active = db.BooleanField(default=True)
    confirmed_at = db.DateTimeField()
    roles = db.ListField(db.ReferenceField(Role), default=[])

app/__init__.py
import os.path as op

from flask import Flask
from flask_admin import Admin
from flask_admin.base import MenuLink
from flask_admin.contrib.fileadmin import FileAdmin
from flask_admin.contrib.mongoengine import ModelView
from flask_babelex import Babel
from flask_bootstrap import Bootstrap
from flask_mail import Mail
from flask_migrate import Migrate
from flask_mongoengine import MongoEngine
from flask_security import MongoEngineUserDatastore, Security
from flask_wtf.csrf import CSRFProtect


# Instantiate Flask extensions
db = MongoEngine()
csrf_protect = CSRFProtect()
mail = Mail()
migrate = Migrate()
babel = Babel()
security = Security()


def create_app(extra_config_settings={}):
    # Create a Flask applicaction.

    # Instantiate Flask
    app = Flask(__name__)

    # Load App Config settings
    # Load common settings from 'app/settings.py' file
    app.config.from_object('app.settings')
    # Load local settings from 'app/local_settings.py'
    app.config.from_object('app.local_settings')
    # Load extra config settings from 'extra_config_settings' param
    app.config.update(extra_config_settings)

    # Setup db Mongo
    db.init_app(app)

    # Setup Flask-Mail
    mail.init_app(app)

    # Setup WTForms CSRFProtect
    csrf_protect.init_app(app)

    # Register blueprints
    from app.views.public_views import public_blueprint
    app.register_blueprint(public_blueprint)
    from app.views.members_views import members_blueprint
    app.register_blueprint(members_blueprint)

    # Setup an error-logger to send emails to app.config.ADMINS
    init_email_error_handler(app)

    # Setup Flask-secure
    from .models.user_models import User, Role
    app.user_datastore = MongoEngineUserDatastore(db, User, Role)
    security.init_app(app, app.user_datastore)
    # datastore.create_user(email='matt@nobien.net', password='password')

    Bootstrap(app)  # Initialize flask_bootstrap

    babel.init_app(app)  # Initialize flask_babelex

    # Define bootstrap_is_hidden_field for flask-bootstrap's bootstrap_wtf.html
    from wtforms.fields import HiddenField

    def is_hidden_field_filter(field):
        return isinstance(field, HiddenField)

    app.jinja_env.globals['bootstrap_is_hidden_field'] = is_hidden_field_filter

    # Setup Flask-admin
    class AdminUserView(ModelView):
        can_create = False
        column_exclude_list = ('password')
        form_overrides = dict(password=HiddenField)

    admin = Admin(app, template_mode='bootstrap3')
    admin.add_view(AdminUserView(User))
    admin.add_view(ModelView(Role))
    path = op.join(op.dirname(__file__), 'static')
    admin.add_view(FileAdmin(path, '/static/', name='Files'))
    admin.add_link(MenuLink(name='Profile', endpoint='members.member_page'))
    admin.add_link(MenuLink(name='Logout', endpoint='security.logout'))

    return app


def init_email_error_handler(app):
    # Initialize a logger to send emails on error-level messages.
    # Unhandled exceptions will now send an email message to app.config.ADMINS.
    if app.debug:
        return  # Do not send error emails while developing

    # Retrieve email settings from app.config
    host = app.config['MAIL_SERVER']
    port = app.config['MAIL_PORT']
    from_addr = app.config['MAIL_DEFAULT_SENDER']
    username = app.config['MAIL_USERNAME']
    password = app.config['MAIL_PASSWORD']
    secure = () if app.config.get('MAIL_USE_TLS') else None

    # Retrieve app settings from app.config
    to_addr_list = app.config['ADMINS']
    subject = app.config.get('APP_SYSTEM_ERROR_SUBJECT_LINE', 'System Error')

    # Setup an SMTP mail handler for error-level messages
    import logging
    from logging.handlers import SMTPHandler

    mail_handler = SMTPHandler(
        mailhost=(host, port),  # Mail host and port
        fromaddr=from_addr,  # From address
        toaddrs=to_addr_list,  # To address
        subject=subject,  # Subject line
        credentials=(username, password),  # Credentials
        secure=secure,
    )

    # Log errors using: app.logger.error('Some error message')
    mail_handler.setLevel(logging.ERROR)
    app.logger.addHandler(mail_handler)

app/views/members_views.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_security import login_required, current_user
from app import babel
from flask import current_app as app
import gettext

members_blueprint = Blueprint('members', __name__, template_folder='templates')


@babel.localeselector
def get_locale():
    translations = [str(translation) for translation in
                    babel.list_translations()]
    return request.accept_languages.best_match(translations)


def set_lang(lang):
    i18n_dir = app.config['BABEL_TRANSLATION_DIRECTORIES']
    gettext.install('lang', i18n_dir)
    trans_file = i18n_dir + lang + '/LC_MESSAGES/flask_security'
    tr = gettext.translation(trans_file, 'locale',  languages=[lang])
    tr.install(True)
    app.jinja_env.install_gettext_translations(tr)


@members_blueprint.before_app_first_request
def init_my_blueprint():
    if not app.user_datastore.get_user('user@example.com'):
        app.user_datastore.create_user(email='user@example.com',
                                       password='Password1')
    if not app.user_datastore.get_user('admin@example.com'):
        app.user_datastore.create_role(name="admin")
        app.user_datastore.create_user(email='admin@example.com',
                                       password='Password1', roles=['admin'])


@members_blueprint.before_app_request
def before_request():
    lang = get_locale()
    lang = lang if lang else app.config['BABEL_DEFAULT_LOCALE']
    set_lang(lang)

    if request.path.startswith('/admin'):
        if current_user.is_authenticated:
            if not current_user.has_role("admin"):
                return redirect(url_for('security.logout'))
        else:
            return redirect(url_for('security.login'))


@members_blueprint.route('/members/')
@login_required
def member_page():
    return render_template('members/profile.html')

app/views/public_views.py
from flask import Blueprint, render_template

public_blueprint = Blueprint('public', __name__, template_folder='templates')


@public_blueprint.route('/')
def home_page():
    return render_template('public/home_page.html')

app/templates/layout.html
{% extends "bootstrap/base.html" %}
{% block title %}This is an example page{% endblock %}
{% import "bootstrap/fixes.html" as fixes %}
{% block head %}
  {{super()}}
  {{fixes.ie8()}}
{% endblock %}

{% block styles %}
  {{super()}}
  <link href="/static/css/global.css" rel="stylesheet">
{% endblock %}

{% block body %}

  {% block navbar %}
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/"><span class="glyphicon glyphicon-leaf text-success" aria-hidden="true"></span> {{ config.get('APP_NAME')  }}</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="{{ url_for('public.home_page') }}">{{ _('Home Page') }}</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if current_user.is_authenticated %}
              <li><a href="{{ url_for('members.member_page') }}"><span class="glyphicon glyphicon-user"></span> {{ _('Profile') }}</a></li>
              <li><a href="{{ url_for('security.logout') }}">{{ _('Logout') }}</a></li>
            {% else %}
              <li><a href="{{ url_for('security.register') }}">{{ _('Register') }}</a></li>
              <li><a href="{{ url_for('security.login') }}"><span class="glyphicon glyphicon-log-in"></span>  {{ _('Login') }}</a></li>
            {% endif %}
          </ul>
          {% if current_user.is_authenticated %}
            {% if current_user.has_role("admin") %}
              <a  class="btn btn-danger navbar-btn"href="{{ url_for('admin.index') }}">{{ _('Admin') }}</a>
            {% endif %}
          {% endif %}
        </div><!--/.nav-collapse -->
      </div>
    </nav>

  {% endblock %}


  <div class="container">
    <div id="main-div" class="with-margins">

      {% import "bootstrap/utils.html" as utils %} {{ utils.flashed_messages(dismissible=True, container=False) }}
      {% block content %}{% endblock %}

    </div>
  </div>

  <footer class="footer">
    <div class="container">
      <p class="text-muted">&copy; <script type="text/javascript">var mdate = new Date(); document.write(mdate.getFullYear());</script> {{ config.get('APP_NAME')  }} </p>
    </div>
  </footer>

  {% block scripts %}
    {{super()}}
  {% endblock %}



{% endblock %}

app/templates/members/profile.html
{% extends "layout.html" %}
{% block content %}
  <h2>{%trans%}Profile{%endtrans%}</h2>
  <a href="{{ url_for('security.change_password') }}">{{ _('Change Password') }}</a>
{% endblock %}

app/templates/security/_macros.html
{% macro render_field_with_errors(field) %}
  <div class="form-group">
    {{ field.label }} {{ field(**kwargs)|safe }}
    {% if field.errors %}
      <ul>
        {% for error in field.errors %}
          <li>{{ error }}</li>
        {% endfor %}
      </ul>
    {% endif %}
  </div>
{% endmacro %}

{% macro render_field(field) %}
  <div class="form-group">
    {{ field(**kwargs)|safe }}
  </div>
{% endmacro %}

app/templates/security/_menu.html
{% if security.registerable or security.recoverable or security.confirmable %}
<h2>{{ _('Menu') }}</h2>
<ul>
  <li><a href="{{ url_for_security('login') }}{% if 'next' in request.args %}?next={{ request.args.next|urlencode }}{% endif %}">{{ _('Login') }}</a></li>
  {% if security.registerable %}
  <li><a href="{{ url_for_security('register') }}{% if 'next' in request.args %}?next={{ request.args.next|urlencode }}{% endif %}">{{ _('Register') }}</a><br/></li>
  {% endif %}
  {% if security.recoverable %}
  <li><a href="{{ url_for_security('forgot_password') }}">{{ _('Forgot password') }}</a><br/></li>
  {% endif %}
  {% if security.confirmable %}
  <li><a href="{{ url_for_security('send_confirmation') }}">{{ _('Confirm account') }}</a></li>
  {% endif %}
</ul>
{% endif %}

app/templates/security/_messages.html
{%- with messages = get_flashed_messages(with_categories=true) -%}
  {% if messages %}
    <ul class="flashes">
    {% for category, message in messages %}
      <li class="{{ category }}">{{ message }}</li>
    {% endfor %}
    </ul>
  {% endif %}
{%- endwith %}

app/templates/security/change_password.html
{% extends "layout.html" %}
{% block content %}
  {% from "security/_macros.html" import render_field_with_errors, render_field %}
  {% include "security/_messages.html" %}
  <h1>{{ _('Change password') }}</h1>
  <form action="{{ url_for_security('change_password') }}" method="POST" name="change_password_form">
    {{ change_password_form.hidden_tag() }}
    {{ render_field_with_errors(change_password_form.password, class_="form-control") }}
    {{ render_field_with_errors(change_password_form.new_password, class_="form-control") }}
    {{ render_field_with_errors(change_password_form.new_password_confirm, class_="form-control") }}
    {{ render_field(change_password_form.submit, class_="btn btn-default") }}
  </form>
{% endblock %}

app/templates/security/forgot_password.html
{% extends "layout.html" %}
{% block content %}
  {% from "security/_macros.html" import render_field_with_errors, render_field %}
  {% include "security/_messages.html" %}
  <h1>{{ _('Send password reset instructions') }}</h1>
  <form action="{{ url_for_security('forgot_password') }}" method="POST" name="forgot_password_form">
    {{ forgot_password_form.hidden_tag() }}
    {{ render_field_with_errors(forgot_password_form.email, class_="form-control") }}
    {{ render_field(forgot_password_form.submit, class_="btn btn-primary") }}
  </form>
{% endblock %}

app/templates/security/login_user.html
{% extends "layout.html" %}
{% block content %}
  {% from "security/_macros.html" import render_field_with_errors, render_field %}
  {% include "security/_messages.html" %}
  <h1>{{ _('Login') }}</h1>
  <form class="form" action="{{ url_for_security('login') }}" method="POST" name="login_user_form">
    {{ login_user_form.hidden_tag() }}
    {{ render_field_with_errors(login_user_form.email, class_="form-control") }}
    {{ render_field_with_errors(login_user_form.password, class_="form-control") }}
    {{ render_field_with_errors(login_user_form.remember, class_="") }}
    {{ render_field(login_user_form.next, class_="form-control") }}
    {{ render_field(login_user_form.submit, class_="btn btn-success") }}
  </form>

  {% if security.recoverable %}
    <p class=""><a href="{{ url_for_security('forgot_password') }}"><span class="glyphicon glyphicon-question-sign"></span> {{ _('Forgot password') }}</a></p>
  {% endif %}

{% endblock %}

app/templates/security/register_user.html
{% extends "layout.html" %}
{% block content %}

  {% from "security/_macros.html" import render_field_with_errors, render_field %}
  {% include "security/_messages.html" %}
  <h1>{{ _('Register') }}</h1>
  <form action="{{ url_for_security('register') }}" method="POST" name="register_user_form">
    {{ register_user_form.hidden_tag() }}
    {{ render_field_with_errors(register_user_form.email, class_="form-control") }}
    {{ render_field_with_errors(register_user_form.password, class_="form-control") }}
    {% if register_user_form.password_confirm %}
      {{ render_field_with_errors(register_user_form.password_confirm, class_="form-control") }}
    {% endif %}
    {{ render_field(register_user_form.submit, class_="btn btn-success") }}
  </form>


{% endblock %}

app/templates/security/reset_password.html
{% from "security/_macros.html" import render_field_with_errors, render_field %}
{% include "security/_messages.html" %}
<h1>{{ _('Reset password') }}</h1>
<form action="{{ url_for_security('reset_password', token=reset_password_token) }}" method="POST" name="reset_password_form">
  {{ reset_password_form.hidden_tag() }}
  {{ render_field_with_errors(reset_password_form.password) }}
  {{ render_field_with_errors(reset_password_form.password_confirm) }}
  {{ render_field(reset_password_form.submit) }}
</form>
{% include "security/_menu.html" %}

app/templates/security/send_confirmation.html
{% from "security/_macros.html" import render_field_with_errors, render_field %}
{% include "security/_messages.html" %}
<h1>{{ _('Resend confirmation instructions') }}</h1>
<form action="{{ url_for_security('send_confirmation') }}" method="POST" name="send_confirmation_form">
  {{ send_confirmation_form.hidden_tag() }}
  {{ render_field_with_errors(send_confirmation_form.email) }}
  {{ render_field(send_confirmation_form.submit) }}
</form>
{% include "security/_menu.html" %}

app/templates/security/send_login.html
{% from "security/_macros.html" import render_field_with_errors, render_field %}
{% include "security/_messages.html" %}
<h1>{{ _('Login') }}</h1>
<form action="{{ url_for_security('login') }}" method="POST" name="send_login_form">
  {{ send_login_form.hidden_tag() }}
  {{ render_field_with_errors(send_login_form.email) }}
  {{ render_field(send_login_form.submit) }}
</form>
{% include "security/_menu.html" %}